name: 'code-coverage'
on:
    pull_request:
        branches: [ master,main,release ]

    workflow_dispatch:
jobs:
    backend-code-coverage:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install taipy-core
                run: |
                    mkdir -p ~/.ssh
                    echo "${{ secrets.SSH_KEY_TAIPY_CORE }}" > ~/.ssh/id_ed25519
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    chmod 600 ~/.ssh/id_ed25519
                    pip install git+ssh://git@github.com/avaiga/taipy-core.git

            - name: Install taipy-gui
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_KEY_TAIPY_GUI }}" > ~/.ssh/id_ed25519
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  chmod 600 ~/.ssh/id_ed25519
                  pip install git+ssh://git@github.com/avaiga/taipy-gui.git

            -   name: Install pipenv
                run: |
                    python -m pip install --upgrade pipenv wheel
                    pip install pytest pytest-cov

            -   id: cache-pipenv
                uses: actions/cache@v1
                with:
                    path: ~/.local/share/virtualenvs
                    key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

            -   name: Install dependencies
                run: |
                    pipenv lock
                    pipenv install --system --dev --python 3.9
                    pip install requests openpyxl
                    pip install git+https://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@github.com/avaiga/taipy.git#egg=taipy --pre

            -   name: Build coverage file
                run: |
                    pytest -s --cov=taipy_rest --cov-append --cov-report=xml --cov-report term-missing tests

            -   name: Code coverage
                uses: orgoro/coverage@v2
                with:
                    coverageFile: coverage.xml
                    token: ${{ secrets.GITHUB_TOKEN }}
                    thresholdAll: 0.85
