name: test workflow

on:
  push:
    branches: [ main,release ]
  pull_request:
    branches: [ main,release ]

  workflow_dispatch:
    inputs:
      user-to-notify:
        description: "Github username to notify"
        required: false
        default: ""

jobs:
  test:
    strategy:
      matrix:
        python-versions: ['3.8', '3.9', '3.10']
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Tests
        run: |
          sed -i 's/ssh/https/g' Pipfile
          sed -i 's/git@github/${{ secrets.PERSONAL_TOKEN }}@github/g' Pipfile

          tox -e tests

      - name: Notify user if failed
        if: failure() && github.event_name == 'workflow_dispatch'
        run: |
          if [[ -n "${{ github.event.inputs.user-to-notify }}" ]]; then
            curl "${{ secrets.notify_endpoint }}" -d '{"username": "${{ github.event.inputs.user-to-notify }}", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' -H "Content-Type: application/json"
          fi
        shell: bash
