name: test workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:
    inputs:
      user-to-notify:
        description: "Github username to notify"
        required: false
        default: ""

jobs:
  test:
    timeout-minutes: 30
    strategy:
      matrix:
        python-versions: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Tests
        run: |
          pip install tox
          tox -e tests

      - name: Ensure no usage of manager classes without factory
        if: matrix.python-versions == '3.10' && matrix.os == 'ubuntu-latest'
        run: |
          ! grep -rP '_ScenarioManager(?!Factory)' src
          ! grep -rP '_DataManager(?!Factory)' src
          ! grep -rP '_TaskManager(?!Factory)' src
          ! grep -rP '_PipelineManager(?!Factory)' src
          ! grep -rP '_JobManager(?!Factory)' src
          ! grep -rP '_CycleManager(?!Factory)' src

      - name: Notify user if failed
        if: failure() && github.event_name == 'workflow_dispatch'
        run: |
          if [[ -n "${{ github.event.inputs.user-to-notify }}" ]]; then
            curl "${{ secrets.notify_endpoint }}" -d '{"username": "${{ github.event.inputs.user-to-notify }}", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' -H "Content-Type: application/json"
          fi
        shell: bash
